### ISSUE TITLE
Failed to load response from ChatGPT: {"detail":"An error ocurred. Try refreshing your browser."}

### ISSUE THREAD

**Issue by wbo2017** [wong2/chatgpt-google-extension#251] opened 2023-02-12 09:29 UTC
**Describe the bug**
Failed to load response from ChatGPT:
{"detail":"An error ocurred. Try refreshing your browser."}

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 -

**Comment by andyyu1022** [comment] 2023-02-12 10:47
I also encounter the error and it only occurs in my ChatGPT PLUS account.

Failed to load response from ChatGPT:
{"detail":"An error ocurred. Try refreshing your browser."}

**Comment by janfelixvs** [comment] 2023-02-12 11:53
Same

- Windows 
- Brave
- ChatGPT Plus

**Comment by ravensergio** [comment] 2023-02-12 12:05
It is working in the latest version, You can wait for Google to approve it in webstore..or you can build it to the latest version from the repo as the author said until that happens (it could take a few days to approve maybe).

**Comment by wong2** [comment] 2023-02-12 14:36
Close as duplicate of #243

**Closed** 2023-02-12 14:36 UTC

**Comment by Som-DL** [comment] 2024-03-27 07:58
the same issue with my first question
