### ISSUE TITLE
ChatGPT Support does not work in Firefox when using the Paid Plan

### ISSUE THREAD

**Issue by randomsnowflake** [wong2/chatgpt-google-extension#246] opened 2023-02-11 09:05 UTC
**Describe the bug**
- Pay OpenAI $20 per month for the premium service
- Install the Firefox Add-on
- Do a Google search
- Observe error message on the right: `Failed to load response from ChatGPT:{"detail":"An error ocurred. Try refreshing your browser."}`

**Desktop (please complete the following information):**
 - macOS
 - Firefox

**Notes**
- GPT3 works fine
- When ChatGPT is already generating a response in another tab, the error message on Google changes to `Failed to load response from ChatGPT:{"detail":"Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute."}`

**Comment by wong2** [comment] 2023-02-11 09:49
Duplicate of #243

**Closed by wong2** 2023-02-11 09:49 UTC
